ValueSet: IHEXDSauthorSpeciality
Id: 1.2.276.0.76.11.31--20180713132208
Title: "IHE XDS authorSpecialty"
Description: """**authorSpecialty (XDSDocumentEntry or XDSSubmissionSet)**
Represents a specific specialty within a healthcare facility under which the human and/or machines authored the XDS Document or XDS SubmissionSet"""
* insert Meta
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2018-07-13T13:22:08+01:00"
* ^url = "http://ihe-d.de/ValueSets/IHEXDSauthorSpeciality"
* ^identifier.use = #official
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.276.0.76.11.31"
* ^version = "2018-07-13T13:22:08"
* ^immutable = false
* urn:oid:1.2.276.0.76.5.114#010 "FA Allgemeinmedizin"
* urn:oid:1.2.276.0.76.5.114#020 "FA Anästhesiologie"
* urn:oid:1.2.276.0.76.5.114#030 "FA Augenheilkunde"
* urn:oid:1.2.276.0.76.5.114#050 "FA Frauenheilkunde und Geburtshilfe"
* urn:oid:1.2.276.0.76.5.114#060 "FA Hals-, Nasen-, Ohrenheilkunde"
* urn:oid:1.2.276.0.76.5.114#070 "FA Haut- und Geschlechtskrankheiten"
* urn:oid:1.2.276.0.76.5.114#080 "FA Innere Medizin"
* urn:oid:1.2.276.0.76.5.114#091 "SP Kinderkardiologie"
* urn:oid:1.2.276.0.76.5.114#093 "SP Neonatologie"
* urn:oid:1.2.276.0.76.5.114#102 "FA Kinder- und Jugendpsychiatrie und -psychotherapie"
* urn:oid:1.2.276.0.76.5.114#110 "FA Laboratoriumsmedizin"
* urn:oid:1.2.276.0.76.5.114#130 "FA Mund-Kiefer-Gesichts-Chirurgie"
* urn:oid:1.2.276.0.76.5.114#142 "FA Neurologie"
* urn:oid:1.2.276.0.76.5.114#147 "FA Psychiatrie und Psychotherapie"
* urn:oid:1.2.276.0.76.5.114#150 "FA Neurochirurgie"
* urn:oid:1.2.276.0.76.5.114#170 "FA Pathologie"
* urn:oid:1.2.276.0.76.5.114#180 "FA Pharmakologie und Toxikologie"
* urn:oid:1.2.276.0.76.5.114#196 "SP Kinderradiologie"
* urn:oid:1.2.276.0.76.5.114#197 "SP Neuroradiologie"
* urn:oid:1.2.276.0.76.5.114#200 "FA Urologie"
* urn:oid:1.2.276.0.76.5.114#210 "FA Arbeitsmedizin"
* urn:oid:1.2.276.0.76.5.114#220 "FA Nuklearmedizin"
* urn:oid:1.2.276.0.76.5.114#230 "FA Öffentliches Gesundheitswesen"
* urn:oid:1.2.276.0.76.5.114#240 "FA Rechtsmedizin"
* urn:oid:1.2.276.0.76.5.114#250 "FA Hygiene und Umweltmedizin"
* urn:oid:1.2.276.0.76.5.114#271 "FA Neuropathologie"
* urn:oid:1.2.276.0.76.5.114#281 "FA Klinische Pharmakologie"
* urn:oid:1.2.276.0.76.5.114#291 "FA Strahlentherapie"
* urn:oid:1.2.276.0.76.5.114#301 "FA Anatomie"
* urn:oid:1.2.276.0.76.5.114#302 "FA Biochemie"
* urn:oid:1.2.276.0.76.5.114#303 "FA Transfusionsmedizin"
* urn:oid:1.2.276.0.76.5.114#304 "FA Kinderchirurgie"
* urn:oid:1.2.276.0.76.5.114#308 "FA Physiologie"
* urn:oid:1.2.276.0.76.5.114#313 "FA Herzchirurgie"
* urn:oid:1.2.276.0.76.5.114#314 "FA Humangenetik"
* urn:oid:1.2.276.0.76.5.114#330 "FA Physikalische und Rehabilitative Medizin"
* urn:oid:1.2.276.0.76.5.114#341 "FA Kinder-und Jugendmedizin"
* urn:oid:1.2.276.0.76.5.114#359 "Fachzahnarzt für Mikrobiologie"
* urn:oid:1.2.276.0.76.5.114#360 "Fachzahnarzt für Kieferchirurgie (§ 6 Abs. 1 BMV)"
* urn:oid:1.2.276.0.76.5.114#361 "Fachzahnarzt für theoretisch-experimentelle Medizin"
* urn:oid:1.2.276.0.76.5.114#511 "FA Gefäßchirurgie"
* urn:oid:1.2.276.0.76.5.114#512 "FA Orthopädie und Unfallchirurgie"
* urn:oid:1.2.276.0.76.5.114#513 "FA Thoraxchirurgie"
* urn:oid:1.2.276.0.76.5.114#514 "FA Visceralchirurgie"
* urn:oid:1.2.276.0.76.5.114#515 "SP Gynäkologische Onkologie"
* urn:oid:1.2.276.0.76.5.114#516 "SP Gynäkologische Endokrinologie und Reproduktionsmedizin"
* urn:oid:1.2.276.0.76.5.114#517 "SP Spezielle Geburtshilfe und Perinatalmedizin"
* urn:oid:1.2.276.0.76.5.114#518 "FA Sprach-, Stimm- und kindliche Hörstörungen"
* urn:oid:1.2.276.0.76.5.114#521 "FA Innere Medizin und (SP) Angiologie"
* urn:oid:1.2.276.0.76.5.114#522 "FA Innere Medizin und (SP) Endokrinologie und Diabetologie"
* urn:oid:1.2.276.0.76.5.114#523 "FA Innere Medizin und (SP) Gastroenterologie"
* urn:oid:1.2.276.0.76.5.114#524 "FA Innere Medizin und (SP) Hämatologie und Onkologie"
* urn:oid:1.2.276.0.76.5.114#525 "FA Innere Medizin und (SP) Kardiologie"
* urn:oid:1.2.276.0.76.5.114#526 "FA Innere Medizin und (SP) Nephrologie"
* urn:oid:1.2.276.0.76.5.114#527 "FA Innere Medizin und (SP) Pneumologie"
* urn:oid:1.2.276.0.76.5.114#528 "FA Innere Medizin und (SP) Rheumatologie"
* urn:oid:1.2.276.0.76.5.114#530 "SP Kinder-Hämatologie und -Onkologie"
* urn:oid:1.2.276.0.76.5.114#531 "SP Neuropädiatrie"
* urn:oid:1.2.276.0.76.5.114#532 "FA Mikrobiologie, Virologie und Infektionsepidemiologie"
* urn:oid:1.2.276.0.76.5.114#533 "SP Forensische Psychiatrie"
* urn:oid:1.2.276.0.76.5.114#534 "FA Psychosomatische Medizin und Psychotherapie"
* urn:oid:1.2.276.0.76.5.114#535 "FA Radiologie (neue (M-)WBO)"
* urn:oid:1.2.276.0.76.5.114#542 "FA Plastische und Ästhetische Chirurgie"
* urn:oid:1.2.276.0.76.5.114#544 "FA Allgemeinchirurgie"
* $QualifikationenNichtAerztlicherAutoren#1 "Gesundheits- Sozial-, Sportmanagement"
* $QualifikationenNichtAerztlicherAutoren#2 "Arzthilfe, Praxisorganisation, -verwaltung"
* $QualifikationenNichtAerztlicherAutoren#3 "Kaufmann/-frau - Gesundheitswesen"
* $QualifikationenNichtAerztlicherAutoren#4 "Medizinischer Fachangestellter"
* $QualifikationenNichtAerztlicherAutoren#6 "Zahnmedizinischer Fachangestellter"
* $QualifikationenNichtAerztlicherAutoren#7 "Arztsekretär"
* $QualifikationenNichtAerztlicherAutoren#8 "Sozial-, Gesundheitsmanagement"
* $QualifikationenNichtAerztlicherAutoren#9 "Gesundheitsaufseher / Hygienekontrolleur"
* $QualifikationenNichtAerztlicherAutoren#10 "Assistent Gesundheits- und Sozialwesen"
* $QualifikationenNichtAerztlicherAutoren#11 "Beamte Sozialversicherung"
* $QualifikationenNichtAerztlicherAutoren#12 "Beamte Sozialverwaltung"
* $QualifikationenNichtAerztlicherAutoren#13 "Betriebswirt  Sozialversicherung"
* $QualifikationenNichtAerztlicherAutoren#14 "Gesundheitsmanager"
* $QualifikationenNichtAerztlicherAutoren#15 "Sozialökonom, -wirt"
* $QualifikationenNichtAerztlicherAutoren#16 "Sozialversicherungsfachangestellte"
* $QualifikationenNichtAerztlicherAutoren#17 "Sportmanagement"
* $QualifikationenNichtAerztlicherAutoren#18 "Sportassistent"
* $QualifikationenNichtAerztlicherAutoren#19 "Fachwirt Fitness"
* $QualifikationenNichtAerztlicherAutoren#20 "Sport- und Fitnesskaufmann"
* $QualifikationenNichtAerztlicherAutoren#21 "Sportmanager, Sportökonom"
* $QualifikationenNichtAerztlicherAutoren#22 "nichtärztliche medizinische Analyse, Beratung, Pflege, Therapie"
* $QualifikationenNichtAerztlicherAutoren#23 "Gesundheitsberatung, -förderung"
* $QualifikationenNichtAerztlicherAutoren#24 "Assistenten für Gesundheitstourismus,  -prophylaxe"
* $QualifikationenNichtAerztlicherAutoren#25 "Diätassistent"
* $QualifikationenNichtAerztlicherAutoren#26 "Gesundheitsförderer, -pädagoge"
* $QualifikationenNichtAerztlicherAutoren#27 "Gesundheitswissenschaftler"
* $QualifikationenNichtAerztlicherAutoren#28 "Oekotrophologe"
* $QualifikationenNichtAerztlicherAutoren#29 "Tai-Chi-Chuan- und Qigong-Lehrer"
* $QualifikationenNichtAerztlicherAutoren#30 "Yogalehrer"
* $QualifikationenNichtAerztlicherAutoren#31 "Sportfachmann"
* $QualifikationenNichtAerztlicherAutoren#32 "Sportwissenschaftler"
* $QualifikationenNichtAerztlicherAutoren#33 "Kranken-, Altenpflege, Geburtshilfe"
* $QualifikationenNichtAerztlicherAutoren#34 "Altenpflegehelfer"
* $QualifikationenNichtAerztlicherAutoren#35 "Altenpfleger"
* $QualifikationenNichtAerztlicherAutoren#36 "Fachkraft Pflegeassistenz"
* $QualifikationenNichtAerztlicherAutoren#37 "Gesundheits- und Kinderkrankenpfleger"
* $QualifikationenNichtAerztlicherAutoren#38 "Gesundheits- und Krankenpflegehelfer"
* $QualifikationenNichtAerztlicherAutoren#39 "Gesundheits- und Krankenpfleger"
* $QualifikationenNichtAerztlicherAutoren#40 "Haus- und Familienpfleger"
* $QualifikationenNichtAerztlicherAutoren#41 "Hebamme / Entbindungspfleger"
* $QualifikationenNichtAerztlicherAutoren#42 "Heilerziehungspfleger"
* $QualifikationenNichtAerztlicherAutoren#43 "Helfer Altenpflege"
* $QualifikationenNichtAerztlicherAutoren#44 "Helfer stationäre Krankenpflege"
* $QualifikationenNichtAerztlicherAutoren#45 "Heilerziehungspflegehelfer"
* $QualifikationenNichtAerztlicherAutoren#46 "Pflegewissenschaftler"
* $QualifikationenNichtAerztlicherAutoren#47 "Nichtärztliche Behandlung, Therapie (außer Psychotherapie)"
* $QualifikationenNichtAerztlicherAutoren#48 "Akademischer Sprachtherapeut"
* $QualifikationenNichtAerztlicherAutoren#49 "Atem-, Sprech- und Stimmlehrer"
* $QualifikationenNichtAerztlicherAutoren#50 "Ergotherapeut"
* $QualifikationenNichtAerztlicherAutoren#51 "Fachangestellter für Bäderbetriebe"
* $QualifikationenNichtAerztlicherAutoren#52 "Heilpraktiker"
* $QualifikationenNichtAerztlicherAutoren#53 "Klinischer Linguist"
* $QualifikationenNichtAerztlicherAutoren#54 "Kunsttherapeut"
* $QualifikationenNichtAerztlicherAutoren#55 "Logopäde"
* $QualifikationenNichtAerztlicherAutoren#56 "Masseur und medizinische Bademeister"
* $QualifikationenNichtAerztlicherAutoren#57 "Motologe"
* $QualifikationenNichtAerztlicherAutoren#58 "Musiktherapeut"
* $QualifikationenNichtAerztlicherAutoren#59 "Orthoptist"
* $QualifikationenNichtAerztlicherAutoren#60 "Physiotherapeut"
* $QualifikationenNichtAerztlicherAutoren#61 "Podologe"
* $QualifikationenNichtAerztlicherAutoren#62 "Sporttherapeut"
* $QualifikationenNichtAerztlicherAutoren#63 "Sprechwissenschaftler"
* $QualifikationenNichtAerztlicherAutoren#64 "Staatlich anerkannter Sprachtherapeut"
* $QualifikationenNichtAerztlicherAutoren#65 "Stomatherapeut"
* $QualifikationenNichtAerztlicherAutoren#66 "Tanz- und Bewegungstherapeut"
* $QualifikationenNichtAerztlicherAutoren#68 "Sozialtherapeut"
* $QualifikationenNichtAerztlicherAutoren#69 "Pharmazeutische Beratung, Pharmavertrieb"
* $QualifikationenNichtAerztlicherAutoren#70 "Apotheker /Fachapotheker"
* $QualifikationenNichtAerztlicherAutoren#71 "Pharmazeut"
* $QualifikationenNichtAerztlicherAutoren#72 "Pharmazeutisch-technischer Assistent – PTA"
* $QualifikationenNichtAerztlicherAutoren#73 "Pharmazeutisch-kaufmännischer Angestellter"
* $QualifikationenNichtAerztlicherAutoren#74 "Psychologische Analyse, Beratung, Therapie"
* $QualifikationenNichtAerztlicherAutoren#75 "Gesundheits- und Rehabilitationspsychologe"
* $QualifikationenNichtAerztlicherAutoren#76 "Kinder- und Jugendpsychotherapeut"
* $QualifikationenNichtAerztlicherAutoren#77 "Klinischer Psychologe"
* $QualifikationenNichtAerztlicherAutoren#78 "Kommunikationspsychologe"
* $QualifikationenNichtAerztlicherAutoren#79 "Pädagogischer Psychologe"
* $QualifikationenNichtAerztlicherAutoren#80 "Psychoanalytiker"
* $QualifikationenNichtAerztlicherAutoren#81 "Psychologe"
* $QualifikationenNichtAerztlicherAutoren#82 "Psychologischer Psychotherapeut"
* $QualifikationenNichtAerztlicherAutoren#83 "Sportpsychologe"
* $QualifikationenNichtAerztlicherAutoren#84 "Verkehrspsychologe"
* $QualifikationenNichtAerztlicherAutoren#85 "Wirtschaftspsychologe"
* $QualifikationenNichtAerztlicherAutoren#86 "Rettungsdienst"
* $QualifikationenNichtAerztlicherAutoren#87 "Ingenieur Rettungswesen"
* $QualifikationenNichtAerztlicherAutoren#88 "Notfallsanitäter"
* $QualifikationenNichtAerztlicherAutoren#89 "Rettungsassistent"
* $QualifikationenNichtAerztlicherAutoren#90 "Rettungshelfer"
* $QualifikationenNichtAerztlicherAutoren#91 "Rettungssanitäter"
* $QualifikationenNichtAerztlicherAutoren#92 "med. Datenverarbeitung"
* $QualifikationenNichtAerztlicherAutoren#94 "Medizinischer Dokumentar"
* $QualifikationenNichtAerztlicherAutoren#95 "Medizinischer Dokumentationsassistent"
* $QualifikationenNichtAerztlicherAutoren#173 "Fachangestellter f. Medien- und Informationsdienste - Medizinische Dokumentation"
* $QualifikationenNichtAerztlicherAutoren#174 "Medizinischer Informationsmanager"
* $QualifikationenNichtAerztlicherAutoren#96 "Soziales, Pädagogik"
* $QualifikationenNichtAerztlicherAutoren#97 "Kinderbetreuung, -erziehung"
* $QualifikationenNichtAerztlicherAutoren#98 "Pädagoge"
* $QualifikationenNichtAerztlicherAutoren#99 "Kinderdorfmutter, -vater"
* $QualifikationenNichtAerztlicherAutoren#100 "Kinderpfleger"
* $QualifikationenNichtAerztlicherAutoren#101 "Erzieher"
* $QualifikationenNichtAerztlicherAutoren#102 "Erzieher Jugend- und Heimerziehung"
* $QualifikationenNichtAerztlicherAutoren#103 "Lehrer"
* $QualifikationenNichtAerztlicherAutoren#104 "Orientierungs- und Mobilitätslehrer"
* $QualifikationenNichtAerztlicherAutoren#105 "Medien-, Kulturpädagogik"
* $QualifikationenNichtAerztlicherAutoren#106 "Musikpädagoge"
* $QualifikationenNichtAerztlicherAutoren#107 "Sozialberatung, -arbeit"
* $QualifikationenNichtAerztlicherAutoren#108 "Sozialarbeiter / Sozialpädagoge"
* $QualifikationenNichtAerztlicherAutoren#109 "Betreuungskraft / Alltagsbegleiter"
* $QualifikationenNichtAerztlicherAutoren#110 "Gerontologe"
* $QualifikationenNichtAerztlicherAutoren#111 "Psychosozialer Prozessbegleiter"
* $QualifikationenNichtAerztlicherAutoren#112 "Rehabilitationspädagoge"
* $QualifikationenNichtAerztlicherAutoren#113 "Sozialassistent"
* $QualifikationenNichtAerztlicherAutoren#114 "Seelsorge"
* $QualifikationenNichtAerztlicherAutoren#115 "Religionspädagoge"
* $QualifikationenNichtAerztlicherAutoren#116 "Gemeindehelfer, Gemeindediakon"
* $QualifikationenNichtAerztlicherAutoren#117 "Theologe"
* $QualifikationenNichtAerztlicherAutoren#118 "Medizintechnik, Laboranalyse"
* $QualifikationenNichtAerztlicherAutoren#119 "Medizin-, Orthopädie- und Rehatechnik"
* $QualifikationenNichtAerztlicherAutoren#120 "Assistent Medizinische Gerätetechnik"
* $QualifikationenNichtAerztlicherAutoren#121 "Augenoptiker"
* $QualifikationenNichtAerztlicherAutoren#122 "Hörakustiker / Hörgeräteakustiker"
* $QualifikationenNichtAerztlicherAutoren#123 "Hörgeräteakustikermeister"
* $QualifikationenNichtAerztlicherAutoren#124 "Ingenieur Augenoptik"
* $QualifikationenNichtAerztlicherAutoren#125 "Ingenieur - Hörtechnik und Audiologie"
* $QualifikationenNichtAerztlicherAutoren#126 "Ingenieur - Medizintechnik"
* $QualifikationenNichtAerztlicherAutoren#127 "Ingenieur - Orthopädie- und Rehatechnik"
* $QualifikationenNichtAerztlicherAutoren#128 "Medizinphysiker (z.B. in Strahlenmedizin)"
* $QualifikationenNichtAerztlicherAutoren#129 "Orthopädieschuhmacher"
* $QualifikationenNichtAerztlicherAutoren#130 "Orthopädietechnik-Mechaniker"
* $QualifikationenNichtAerztlicherAutoren#131 "Zahntechniker"
* $QualifikationenNichtAerztlicherAutoren#132 "Glasbläser (Fachrichtung Kunstaugen)"
* $QualifikationenNichtAerztlicherAutoren#133 "staatlich geprüfter Techniker der Fachrichtung Medizintechnik"
* $QualifikationenNichtAerztlicherAutoren#134 "Medizinisch-technische Assistenz"
* $QualifikationenNichtAerztlicherAutoren#135 "Anästhesietechnischer Assistent"
* $QualifikationenNichtAerztlicherAutoren#136 "HNO Audiologieassistent"
* $QualifikationenNichtAerztlicherAutoren#137 "Medizinisch-Technischer Assistent Funktionsdiagnostik – MTA-F"
* $QualifikationenNichtAerztlicherAutoren#138 "Medizinisch-Technischer Laboratoriumsassistent – MTA-L"
* $QualifikationenNichtAerztlicherAutoren#139 "Medizinisch-Technischer Radiologieassistent – MTA-R"
* $QualifikationenNichtAerztlicherAutoren#140 "Operationstechnischer Angestellter"
* $QualifikationenNichtAerztlicherAutoren#141 "Operationstechnischer Assistent"
* $QualifikationenNichtAerztlicherAutoren#143 "Zytologieassistent"
* $QualifikationenNichtAerztlicherAutoren#144 "Chemie, naturwissenschaftliche Laboranalyse (außer MTA)"
* $QualifikationenNichtAerztlicherAutoren#145 "Biochemiker (z.B. klinische Chemie)"
* $QualifikationenNichtAerztlicherAutoren#146 "Chemiker (z.B. klinische Chemie)"
* $QualifikationenNichtAerztlicherAutoren#147 "Humangenetiker"
* $QualifikationenNichtAerztlicherAutoren#148 "Mikrobiologe"
* $QualifikationenNichtAerztlicherAutoren#149 "Dienstleistungen am Menschen (außer medizinische)"
* $QualifikationenNichtAerztlicherAutoren#150 "Körperpflege"
* $QualifikationenNichtAerztlicherAutoren#151 "Fachkraft Beauty und Wellness"
* $QualifikationenNichtAerztlicherAutoren#152 "Friseur"
* $QualifikationenNichtAerztlicherAutoren#153 "Kosmetiker"
* $QualifikationenNichtAerztlicherAutoren#154 "Bestattungswesen"
* $QualifikationenNichtAerztlicherAutoren#155 "Bestattungsfachkraft"
* $QualifikationenNichtAerztlicherAutoren#156 "Berufe aus sonstigen Berufsfeldern"
* $QualifikationenNichtAerztlicherAutoren#157 "Umwelt"
* $QualifikationenNichtAerztlicherAutoren#165 "Jurist"
* $QualifikationenNichtAerztlicherAutoren#169 "Taxifahrer bei Krankentransport"